Oodle/Oodle/Models/Assignment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Assignment")]
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            Documents = new HashSet<Document>();
            Grades = new HashSet<Grade>();
            Questions = new HashSet<Question>();
        }

        public int AssignmentID { get; set; }

        public int ClassID { get; set; }

        [Required]
        [StringLength(128)]
        public string Name { get; set; }

        [StringLength(512)]
        public string Description { get; set; }

        public DateTime? StartDate { get; set; }

        [MyDate(ErrorMessage = "Invalid date")]
        public DateTime? DueDate { get; set; }

        public int Weight { get; set; }

        public virtual Class Class { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}

public class MyDateAttribute : ValidationAttribute
{
    public override bool IsValid(object value)// Return a boolean value: true == IsValid, false != IsValid
    {
        DateTime d = Convert.ToDateTime(value);
        return d >= DateTime.Now; //Dates Greater than or equal to today are valid (true)
    }
}

Oodle/Oodle/Models/Grade.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Grade
    {
        [Key]
        public int GradesID { get; set; }

        public int UsersID { get; set; }

        public int AssignmentID { get; set; }

        [StringLength(64)]
        public string Grader { get; set; }

        [StringLength(256)]
        public string Comment { get; set; }

        [Column("Grade")]
        public int Grade1 { get; set; }

        public virtual Assignment Assignment { get; set; }

        public virtual User User { get; set; }
    }
}

Oodle/Oodle/Models/Tasks.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Tasks
    {
        [Key]
        public int TasksID { get; set; }

        public int ClassID { get; set; }

        [StringLength(512)]
        public string Description { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? DueDate { get; set; }

        public virtual Class Class { get; set; }
    }
}

Oodle/Oodle/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Oodle.Models;
using Oodle.Models.ViewModels;
using Oodle.Models.Repos;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Configuration;
using System.Diagnostics;
using Oodle.Utility;
using System.Text.RegularExpressions;

namespace Oodle.Controllers
{
    [Authorize]
    public class TeachersController : Controller 
    {
        //Slack access
        private SlackManager slack = new SlackManager();


        //Regular database
        //private Model1 db = new Model1();
        //Repo for mocking database
        private IOodleRepository db;

        public TeachersController(IOodleRepository repo)
        {
            this.db = repo;
        }

        public ActionResult test(int classID)
        {
            var idid = User.Identity.GetUserId();

            User user = db.Users.Where(a => a.IdentityID == idid).FirstOrDefault();
            UserRoleClass urc = db.UserRoleClasses.Where(s => s.UsersID == user.UsersID && s.ClassID == classID).FirstOrDefault();

            if (urc == null || urc.RoleID != 0)
            {
                return RedirectToAction("Index", "Class", new { classId = classID });
            }
            return null;
        }


        public ActionResult Index(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }
            var teacher = getTVM(classID);

            return View("index", "_TeacherLayout", teacher);
        }











        [HttpPost]
        [ActionName("Index")]
        public ActionResult IndexPost(int classID)
        {
            if (test(classID) != null)
            {

                return test(classID);
            }


            var teacher = getTVM(classID);
            var classes = db.Classes.ToList(); // list of all classes



            ViewBag.classList = classes;
            foreach (var item in classes) // Loop through List with foreach
            {
                System.Diagnostics.Debug.WriteLine(item);
            }


            System.Diagnostics.Debug.WriteLine(classes);


            ViewBag.RequestMethod = "POST";

            string desc = Request.Form["description"];
            string id = Request.Form["classID"];


            if (test(classID) != null)
            {
                return test(classID);
            }
            var note = new Notes();

            note.NotesID = db.Tasks.Count() + 1;
            note.Description = desc;
            note.ClassID = classID;


            db.AddNote(note);
            db.SaveChanges();


            teacher.Notes = db.Notes.ToList();

            return View("index", "_TeacherLayout", teacher);
        }












        public ActionResult Accept(int classID, int userID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            db.UserRoleClasses.Where(i => i.UsersID == userID & i.ClassID == classID).ToList().ForEach(x => x.RoleID = 2);
            db.SaveChanges();

            //get user and class
            User user = db.Users.Where(i => i.UsersID == userID).FirstOrDefault();
            Class c = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();
            //Send request to slack for user to join the group
            //slack.JoinChannel(user.Email, c.Name);

            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult Reject(int classID, int userID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            db.RemoveURC(db.UserRoleClasses.Where(i => i.UsersID == userID & i.ClassID == classID).FirstOrDefault());
            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult Edit(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            ViewBag.id = classID;

            var teacher = getTVM(classID);

            return View("Edit", "_TeacherLayout", teacher);
        }

        public ActionResult EditClass()
        {
            ViewBag.RequestMethod = "POST";

            string name = Request.Form["name"];
            string desc = Request.Form["description"];
            int classID = int.Parse(Request.Form["classID"]);

            if (test(classID) != null)
            {
                return test(classID);
            }

            db.Classes.Where(i => i.ClassID == classID).ToList().ForEach(x => x.Name = name);
            db.Classes.Where(i => i.ClassID == classID).ToList().ForEach(x => x.Description = desc);

            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult AddNotifToClass(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            ViewBag.id = classID;

            var teacher = getTVM(classID);

            return View("AddNotifToClass", "_TeacherLayout", teacher);
        }

        public ActionResult SaveNotif()
        {
            ViewBag.RequestMethod = "POST";
            string notif = Request.Form["notification"];
            int classID = int.Parse(Request.Form["classID"]);

            if (test(classID) != null)
            {
                return test(classID);
            } 

            Class hasSlack = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();


            if (!(string.IsNullOrEmpty(notif)))
            {
                if (!hasSlack.SlackName.Equals("%"))
                {
                    slack.SlackNotif(notif, hasSlack.SlackName);
                }
                AddNotification(notif, classID);
            }


            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult RemoveNotif(int classID, int notifID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            ClassNotification cNotif = db.ClassNotifications.Where(n => n.ClassID == classID 
                                                                && n.ClassNotificationID == notifID).FirstOrDefault();
            if(cNotif == null)
            {
                return RedirectToAction("Index", new { classId = classID });
            }

            var teacher = getTVM(classID);
            teacher.rNotif = cNotif;

            return View("RemoveNotif", "_TeacherLayout", teacher);
        }

        public ActionResult RemoveNotification(int classID, int notifID)
        {
            
            if (test(classID) != null)
            {
                return test(classID);
            }

            ClassNotification notif = db.ClassNotifications.Where(n => n.ClassID == classID
                                                    && n.ClassNotificationID == notifID).FirstOrDefault();
            db.RemoveNotif(notif);
            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        private void AddNotification(string notif, int classID)
        {
            ClassNotification cNotif = new ClassNotification();
            cNotif.Notification = notif;
            cNotif.TimePosted = DateTime.Now;
            cNotif.ClassID = classID;
            db.AddNotif(cNotif);
            db.SaveChanges();           
        }

        public ActionResult Delete(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            var list = db.UserRoleClasses.Where(i => i.ClassID == classID);
            Class hasSlack = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();
            foreach (var i in list)
            {
                db.RemoveURC(i);
            }

            //classID = 1;
            if (!hasSlack.SlackName.Equals("%"))
            {
                slack.DeleteChannel(hasSlack.SlackName);
            }

            db.RemoveClass(db.Classes.Where(i => i.ClassID == classID).FirstOrDefault());

            db.SaveChanges();


            return RedirectToAction("List", "Class");
        }


        public ActionResult MakeGrade()
        {
            return View("MakeGrade", "_TeacherLayout");
        }

        /*
         * Method returns the ViewRoster Html object and loads in 3 db models into the view.
         * 
         */
        public ActionResult ViewRoster(int classID)
        {
            var classes = db.Classes.ToList(); // list of all classes
            var user = db.Users.ToList(); // list of all users
            var roles = db.UserRoleClasses.ToList(); // List of all Roles


            ViewBag.name = User.Identity.GetUserName(); // testing viewbag output

            var urcL = db.UserRoleClasses.Where(i => i.RoleID == 0);
            var list = new List<int>();
            foreach (var i in urcL)
            {
                list.Add(i.UsersID);
            }
            var request = db.Users.Where(i => list.Contains(i.UsersID)).ToList();
            var request2 = db.Users.Where(i => list.Contains(i.UsersID)).ToList();

            var teacher = new TeacherVM(classes, user, roles);  // New TeacherVM using the list of classes and user


Oodle/Oodle/Views/Teachers/AddQuestion.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddQuestion</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Add a Question to Quiz: @Model.quiz.QuizName</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
            @Html.HiddenFor(Model => Model.question.QuizID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.question.Points, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.question.Points, new { htmlAttributes = new { @class = "form-control", min = 0, step = 1 } })
                    @Html.ValidationMessageFor(model => model.question.Points, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.question.QuestionText, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.question.QuestionText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.question.QuestionText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer3, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer4, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer4, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer4, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(Model => Model.answer.QuestionID, new { @value = "-1" })
            
            <div class="form-group">
                @Html.LabelFor(model => model.answer.CorrectAnswer, htmlAttributes: new { @class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.answer.CorrectAnswer, new { htmlAttributes = new { @class = "form-control", min = 1, max = 4, step = 1 } })
                    @Html.ValidationMessageFor(model => model.answer.CorrectAnswer, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add Another Question" formaction=@Url.Action("AddAnother") formmethod="post" class="btn btn-default" />
                    <input type="submit" value="Finish" formaction=@Url.Action("SaveQuestion") formmethod="post" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to Quiz View", "ViewQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, null)
    </div>
</body>
</html>

Oodle/Oodle/Views/Teachers/CreateAssignment.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "CreateAssignment";
}


<div class="form-style-6">
    <form method="post" action="CreateAssignmentAction" onsubmit="return compareTime()" name="formT">
        <div>
            <h1>Create an Assignment</h1>

            <label for="name">Name of Assignment:</label><br />
            <input type="text" name="name" placeholder="e.g., Assignment one, history of modernism" value="" required maxlength="128" /><br />
            <input type="hidden" name="classID" value="@Model.cl.ClassID" />

            <label for="description">Description of your Assignment:</label> <br />
            <textarea name="description" placeholder="e.g., please read chapter four and attach a word document of your answers to the questions at the end of the chapter." required maxlength="512"></textarea> <br />

            <label for="weight">Weight of Grade:</label> <br />
            <input type="number" name="weight" placeholder="0" value="" max="1000" min="0" required /><br />

            <br />
            <label for="startDate">Start Date</label><br />
            <input type="datetime-local" name="startDate" value="@DateTime.Now" required />

            <br />
            <label for="dueDate">Due Date</label><br />
            <input type="datetime-local" name="dueDate" value="@DateTime.Now" required min="@DateTime.Now.ToString("dd-mm-yyyyThh:mm:ss")" />
        </div>
        <div>
            <input type="submit" name="submit" value="Create Assignment" />
        </div>
    </form>
</div>


<script>
    function compareTime() {
        var x = document.forms["formT"]["dueDate"].value;
        var y = document.forms["formT"]["startDate"].value;

        if (new Date(x) <= new Date(y)){
            alert("The due date must be after the start date.");
        }
        return new Date(x) > new Date(y); // true if time1 is later

    }
</script>






Oodle/Oodle/Views/Teachers/EditQuiz.cshtml
@model Oodle.Models.ViewModels.TeacherVM


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Edit Quiz: @Model.quiz.QuizName</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.quiz.QuizID)
        <div class="form-group">
            @Html.LabelFor(model => model.quiz.QuizName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quiz.QuizName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quiz.QuizName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quiz.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quiz.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quiz.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quiz.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quiz.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quiz.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.quiz.ClassID)


        <div class="form-group">
            @Html.LabelFor(model => model.quiz.IsHidden, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.quiz.IsHidden)
                    @Html.ValidationMessageFor(model => model.quiz.IsHidden, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @Html.HiddenFor(model => model.quiz.TotalPoints)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Edits" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back to Quiz View", "ViewQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, null)
    </div>

Oodle/Oodle/Views/Teachers/Grades.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Grades";
}

<h2>Grades</h2>
<div class="slide-toggle2">
    <div>
        <br />
        <!-- fluid -->
        <div class="box-toggle">
            @if(true){
                var number = 0;
                var t = 0;
                foreach (var i in Model.users.ToList())
                {
                    var test = Model.perUser[t];
                    t++;
                    <div class="contorol">

                        <h3>
                            @Html.DisplayFor(Name => i.UserName)
                        </h3>
                        <span class="toggle-info pull-left">
                            <i class="fa fa-plus"></i>
                        </span>
                    </div>
                    <div class="content-box">
                        <div class="black">
                            @for (int i2 = 0; i2 < Model.documents.Count(); i2++)
                            {
                                if(Model.documents[i2] != null) { 
                                    var doc = Model.documents[i2];
                                    var classID = Model.cl.ClassID;
                                    var documentID = doc.Id;
                                    var assignmentID = doc.AssignmentID;
                                    var submittedDate = doc.Date;
                                    var dueDate = doc.Assignment.DueDate;
                                    var late = test.Late[i2];
                                    var stat = test.stat[i2];


                                    <div class="contorol padded">

                                        <div>@doc.Assignment.Name</div>

                                        <a href="@Url.Action("Grade", "Teachers", new { classID = classID, documentID = documentID, assignmentID = assignmentID })"> Grade Assignment </a>
                                        <div>
                                            Current Grade: @if (doc.Grade == -1)
                                            {
                                                <div>Not yet graded.</div>
                                            }
                                            else
                                            {
                                                @Html.DisplayFor(Grade => doc.Grade);
                                            }
                                        </div>
                                    

                                        @if(!stat) {
                                            <div class="dateRight2 late">
                                                Submitted @Html.DisplayFor(date => late.Days) days, @Html.DisplayFor(date => late.Hours) hours, and @Html.DisplayFor(date => late.Minutes) minutes late.
                                            </div>
                                        }
                                        @if(stat) {
                                            <div class="dateRight2 early">
                                                Submitted @Html.DisplayFor(date => late.Days) days, @Html.DisplayFor(date => late.Hours) hours, and @Html.DisplayFor(date => late.Minutes) minutes early.
                                            </div>
                                        }
                                    </div>
                                    <hr />
                                }
                            }
                        </div>
                    </div>
                    <div>
                        Average on Graded Assignments Based off Weights:
                        @Model.classGrade[number]
                    </div>
                    number = number + 1;

                    <hr />
                }
            }
        </div>
    </div>
</div>
<div>

</div>
@section scripts
{
    <script type="text/javascript" src="~/Scripts/scriptone.js"></script>
}

Oodle/Oodle/Views/Teachers/RemoveNotif.cshtml
@model Oodle.Models.ViewModels.TeacherVM


<div class="removeNotif">
    <h1>Remove Notification</h1>
    <p>Click the Remove Notification button to confirm removing, otherwise click the back button to go back to your class page</p>
    <p>Notification To Remove: @Model.rNotif.Notification</p>

    @Html.ActionLink("Back", "Index", "Teachers", new { ClassID = Model.rNotif.ClassID }, new { @class = "" })

    @Html.ActionLink("Remove Notification", "RemoveNotification", "Teachers", new { classID = Model.rNotif.ClassID, notifID = Model.rNotif.ClassNotificationID }, new { @class = "" })
    <p></p>

</div>

Oodle/Oodle/Views/Teachers/RemoveQuiz.cshtml
@model Oodle.Models.ViewModels.TeacherVM


<div class="removeNotif">
    <h1>Delete Quiz</h1>
    <p>Click the Delete Quiz button to confirm deleting the quiz, otherwise click the back button to the quiz page</p>
    <p>Quiz To Remove: @Model.quiz.QuizName</p>

    @Html.ActionLink("Back", "ViewQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, new { @class = "" })

    @Html.ActionLink("Delete Quiz", "DeleteQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, new { @class = "" })
    <p></p>

</div>

Oodle/Oodle/Views/Teachers/SubmissionView.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "SubmissionView";
}

<h2>Submissions</h2>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
   
</head>
@using (Html.BeginForm("DownloadFile", "Students", FormMethod.Post))
{
    <input type="hidden" id="hfFileId" name="FileId" />
    <input type="submit" id="btnDownload" value="Download" style="display:none" />
}
<hr />
<table cellpadding="0" cellspacing="0" class="responsive-table">
    <tr>
        <th style="width:50px">Student</th>
        <th style="width:120px">File Name</th>
        <th style="width:120px">Grade Link</th>
        <th style="width:80px">Download</th>
    </tr>
    @if (Model.documents.Count() > 0)
    {
        for (int i = 0; i < Model.documents.Count(); i++)
        {
            var file = Model.documents[i];
            var user = Model.users[i];
            var classID = Model.cl.ClassID;
            var documentID = Model.documents[i].Id;
            var assignmentID = Model.assignment.FirstOrDefault().AssignmentID;
            <tr>
                <td>@user.UserName</td>
                <td>@file.Name</td>
                <td><a href="@Url.Action("Grade", "Teachers", new {classID = classID,documentID = documentID,assignmentID = assignmentID})"> Grade </a></td>
                <td><a href="javascript:;" onclick="DownloadFile(@file.Id)">Download</a></td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td colspan="3">&nbsp;</td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    function DownloadFile(fileId) {
        $("#hfFileId").val(fileId);
        $("#btnDownload")[0].click();
    };
</script>

Oodle/Oodle/Views/Teachers/Tasks.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Tasks";
}
<center><h2>Tasks</h2></center>


<center>
    <a class="buttonReject" href="@Url.Action("CreateTask", "Teachers", new { classID = Model.cl.ClassID } )">
        Create a Task
    </a>
</center>
<br />

<div>
    @foreach (var i in Model.Tasks)
    {
        if (i.ClassID == Model.cl.ClassID)
        {
            var tsk = i;
            <div class="block">
                <div class="classItem" style='@(DateTime.Now>tsk.DueDate ?"background-color:red":"")'>
                    <div class="description">
                        @Html.DisplayFor(Desc => tsk.Description)
                    </div>
                    <div class="dateLeft" style="color:#17252A">
                        Start Date: @Html.DisplayFor(Desc => tsk.StartDate)
                    </div>
                    <div class="dateRight" style="color:#17252A">
                        Due Date: @Html.DisplayFor(Desc => tsk.DueDate)
                    </div>
                    <a href="@Url.Action("EditTasks", "Teachers", new { classID = Model.cl.ClassID, TasksID = tsk.TasksID })" class="edit">
                        Edit
                    </a>
                </div>
            </div>
            <br />
            <br />
        }

    }
</div>